export enum EventStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  ADDRESS_UNCLEAR = 'ADDRESS_UNCLEAR',
  RESPONSIBILITY_UNCLEAR = 'RESPONSIBILITY_UNCLEAR',
  ASSIGNED = 'ASSIGNED',
  PROCESSING = 'PROCESSING',
  RETURNED = 'RETURNED',
  IN_COORDINATION = 'IN_COORDINATION',
  ESCALATED = 'ESCALATED',
  COMPLETED = 'COMPLETED',
  CONFIRMED = 'CONFIRMED',
  REJECTED = 'REJECTED',
  CLOSED = 'CLOSED',
  DUPLICATE = 'DUPLICATE',
  MERGED = 'MERGED',
}

export enum SourceCallbackStatus {
  PENDING = 'PENDING',
  CALLBACK_SCHEDULED = 'CALLBACK_SCHEDULED',
  CALLBACK_IN_PROGRESS = 'CALLBACK_IN_PROGRESS',
  CALLBACK_COMPLETED = 'CALLBACK_COMPLETED',
  CALLBACK_FAILED = 'CALLBACK_FAILED',
  EVALUATED = 'EVALUATED',
}

export enum CoordinationStatus {
  NONE = 'NONE',
  PENDING_COORDINATION = 'PENDING_COORDINATION',
  COORDINATING = 'COORDINATING',
  COORDINATED = 'COORDINATED',
}

export enum MergeStrategy {
  AUTO = 'AUTO',
  MANUAL = 'MANUAL',
}

export enum EventType {
  ROAD_OCCUPATION = 'ROAD_OCCUPATION',
  MANHOLE_DAMAGE = 'MANHOLE_DAMAGE',
  NOISE_DISTURBANCE = 'NOISE_DISTURBANCE',
  WATERLOGGING = 'WATERLOGGING',
  GARBAGE = 'GARBAGE',
  FACILITY_DAMAGE = 'FACILITY_DAMAGE',
  OTHER = 'OTHER',
}

export enum UrgencyLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum UserRole {
  RESIDENT = 'RESIDENT',
  GRID_WORKER = 'GRID_WORKER',
  COMMAND_CENTER = 'COMMAND_CENTER',
  DEPARTMENT_STAFF = 'DEPARTMENT_STAFF',
  ADMIN = 'ADMIN',
}

export enum DepartmentType {
  CHENGGUAN = 'CHENGGUAN',
  MUNICIPAL = 'MUNICIPAL',
  PROPERTY = 'PROPERTY',
  TRAFFIC_POLICE = 'TRAFFIC_POLICE',
  ENVIRONMENTAL = 'ENVIRONMENTAL',
  OTHER = 'OTHER',
}

export enum ReturnReason {
  ADDRESS_UNCLEAR = 'ADDRESS_UNCLEAR',
  NOT_OUR_RESPONSIBILITY = 'NOT_OUR_RESPONSIBILITY',
  INSUFFICIENT_INFO = 'INSUFFICIENT_INFO',
  DUPLICATE_EVENT = 'DUPLICATE_EVENT',
  OTHER = 'OTHER',
}

export const URGENCY_DEADLINE_HOURS: Record<UrgencyLevel, number> = {
  [UrgencyLevel.LOW]: 72,
  [UrgencyLevel.MEDIUM]: 48,
  [UrgencyLevel.HIGH]: 24,
  [UrgencyLevel.URGENT]: 4,
};

export const EVENT_TYPE_TO_DEPARTMENT: Record<EventType, DepartmentType> = {
  [EventType.ROAD_OCCUPATION]: DepartmentType.CHENGGUAN,
  [EventType.MANHOLE_DAMAGE]: DepartmentType.MUNICIPAL,
  [EventType.NOISE_DISTURBANCE]: DepartmentType.CHENGGUAN,
  [EventType.WATERLOGGING]: DepartmentType.MUNICIPAL,
  [EventType.GARBAGE]: DepartmentType.CHENGGUAN,
  [EventType.FACILITY_DAMAGE]: DepartmentType.MUNICIPAL,
  [EventType.OTHER]: DepartmentType.OTHER,
};
